on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        name: deploy2nekoweb
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # your build step here
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24.x"

            - name: Install dependencies
              run: npm install --if-present

            - name: Build app
              run: npm run build

            - run: npm install -g serve

            - name: deploy2nekoweb
              uses: indiefellas/deploy2nekoweb@main
              with:
                  nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
                  nekoweb-domain: "laggy.com.br"
                  nekoweb-username: "laggy"
                  directory: "public"
